# Generated by Django 5.0.6 on 2024-06-19 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SongModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=30, verbose_name='название')),
                ('description', models.CharField(max_length=100, verbose_name='описание')),
                ('song_image', models.ImageField(blank=True, upload_to='songs/image/', verbose_name='картинка песни')),
                ('song', models.FileField(upload_to='songs/audio/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
