# Generated by Django 5.0.6 on 2024-06-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songmodel',
            name='song_text',
            field=models.CharField(default=1, max_length=25000, verbose_name='текст песни'),
            preserve_default=False,
        ),
    ]
