# Generated by Django 5.0.6 on 2024-06-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_songmodel_song_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songmodel',
            name='song',
            field=models.FileField(blank=True, upload_to='songs/audio/'),
        ),
    ]
