# Generated by Django 5.0.6 on 2024-06-20 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0005_rename_genre_songgenre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='имя')),
                ('about_user', models.CharField(max_length=123, verbose_name='О себе')),
                ('user_image', models.ImageField(blank=True, upload_to='user/img/', verbose_name='фото пользавателя')),
                ('image', models.ImageField(blank=True, upload_to='banner/img/', verbose_name='фото баннера')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cabinet', to=settings.AUTH_USER_MODEL, verbose_name='пользаватель')),
                ('favorite_genres', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='songs.songgenre', verbose_name='любимый жанр')),
            ],
        ),
    ]
